# SPDX-License-Identifier: GPL-2.0
dtb-y += s5e8825.dtb

dtbo-y += \
    samsung/a26xs/a26xs_ltn_open_w00_r05.dts \
    samsung/a26xs/a26xs_ltn_open_w00_r04.dts \
    samsung/a26xs/a26xs_ltn_open_w00_r02.dts \
    samsung/a26xs/a26xs_ltn_open_w00_r00.dts
